[build-system]
requires = ["setuptools>=64.0", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pyticdb"
description = "A quick reflector for stellar catalogs and other static SQL databases"
authors = [{name="William Fong", email="willfong@mit.edu"}]
readme = "README.rst"
dynamic = ["version"]

dependencies = [
    "sqlalchemy>=2.0",
    "click>=8.0",
    "setuptools>69.5",
    "configurables @ git+https://github.com/mit-kavli-institute/configurables.git",
    "loguru>=0.7.3",
    "psycopg>=3.2.6"
]

[tool.setuptools.dynamic]
version = {attr = "pyticdb.__version__"}


[project.urls]
Home = "https://tessgit.mit.edu/wcfong/pyticdb"

[project.optional-dependencies]
dev = [
    "black>=24.4",
    "hypothesis>=6",
    "hypothesis_fspaths",
    "mypy==1.10",
    "pytest-cov",
    "pytest-mock",
    "pytest-sugar",
    "pytest-xdist",
    "pytest>=8.2",
]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_pattern = ["src/pyticdb/__init__.py:__version__"]
version_source = "tag"
commit_version_number = true
tag_format = "v{version}"
major_on_zero = true
branch = "master"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install build && python -m build"
commit_subject = "chore(release): {version} [skip ci]"
commit_message = "Automatically generated by python-semantic-release"
logging_use_named_masks = false
commit_author = "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

[tool.semantic_release.branches.master]
match = "(master|main)"
prerelease = false

[tool.semantic_release.branches.staging]
match = "staging"
prerelease = true
prerelease_token = "beta"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = [
    "^Merge",
    "^chore",
    "^ci",
    "^docs(?!:)",
]

[tool.semantic_release.changelog.environment]
keep_trailing_newline = true
trim_blocks = true
lstrip_blocks = true

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]